//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHLHTMLReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME_INFO
    {
        public int ID { get; set; }
        public string HOME_TEAM { get; set; }
        public string VISITOR_TEAM { get; set; }
        public Nullable<System.DateTimeOffset> START_TIME { get; set; }
        public Nullable<System.DateTimeOffset> END_TIME { get; set; }
        public string STATUS { get; set; }
        public int HOME_SCORE { get; set; }
        public int VISITOR_SCORE { get; set; }
        public string HomeCode { get; set; }
        public string VisitorCode { get; set; }
        public string GameType { get; set; }
    }
}
