//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHLHTMLReports
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NLPoolEntities : DbContext
    {
        public NLPoolEntities()
            : base("name=NLPoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GAME_INFO> GAME_INFO { get; set; }
        public virtual DbSet<GOALIE_SUMMARY> GOALIE_SUMMARY { get; set; }
        public virtual DbSet<NHL_PLAYER> NHL_PLAYER { get; set; }
        public virtual DbSet<PLAYER_SUMMARY> PLAYER_SUMMARY { get; set; }
    }
}
