//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHLHTMLReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHL_PLAYER
    {
        public int ID { get; set; }
        public string LAST_NAME { get; set; }
        public string FIRST_NAME { get; set; }
        public string TEAM { get; set; }
        public int PLAYER_NUMBER { get; set; }
        public string ELIGIBLE_POSITION { get; set; }
        public bool ACTIVE { get; set; }
        public string TSN_NAME { get; set; }
        public string NHLTeamCode { get; set; }
        public Nullable<int> RotoworldId { get; set; }
        public string YahooKey { get; set; }
    }
}
