//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHLHTMLReports
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLAYER_SUMMARY
    {
        public int ID { get; set; }
        public Nullable<int> GAME_ID { get; set; }
        public string TEAM { get; set; }
        public Nullable<int> PLAYER_NUMBER { get; set; }
        public string POS { get; set; }
        public string PLAYER_NAME { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> A { get; set; }
        public Nullable<int> P { get; set; }
        public Nullable<int> PLUS_MINUS { get; set; }
        public Nullable<int> PN { get; set; }
        public Nullable<int> PIM { get; set; }
        public Nullable<int> TOT { get; set; }
        public Nullable<int> SHF { get; set; }
        public Nullable<int> AVG { get; set; }
        public Nullable<int> PP { get; set; }
        public Nullable<int> SH { get; set; }
        public Nullable<int> EV { get; set; }
        public Nullable<int> S { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<int> MS { get; set; }
        public Nullable<int> HT { get; set; }
        public Nullable<int> GV { get; set; }
        public Nullable<int> TK { get; set; }
        public Nullable<int> BS { get; set; }
        public Nullable<int> FW { get; set; }
        public Nullable<int> FL { get; set; }
        public Nullable<int> FP { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public string GSA1 { get; set; }
        public string GSA2 { get; set; }
        public string GSA3 { get; set; }
        public Nullable<int> W { get; set; }
        public Nullable<int> L { get; set; }
        public Nullable<int> OT { get; set; }
        public Nullable<int> SO { get; set; }
    }
}
